### ISSUE TITLE
Where is the code of how to compute NWD loss?

### ISSUE THREAD

**Issue by wuqiangch** [jwwangchn/NWD#2]
@jwwangchn  Where is the code of how to compute NWD loss? I want to put the losss to my own code. Thanks!

**Comment by jwwangchn** [comment]
Please refer [wasserstein_loss()](https://github.com/jwwangchn/NWD/blob/9ceb60a7067c570ba1f2ce616dcec96d867d143f/mmdet/models/losses/iou_loss.py#L223)

**Comment by wuqiangch** [comment]
@jwwangchn Thanks.

**Comment by zimenglan-sysu-512** [comment]
hi @jwwangchn 
for anchor-based or anchor-free one-stage detector, only use the wasserstein_loss to boost the performace? it seems that label assignment is used for rpn of two-stage detector.
